# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlist',
            name='bucket_items',
        ),
        migrations.AddField(
            model_name='bucketlistitem',
            name='bucketlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bucket.BucketList'),
        ),
    ]
