# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0002_auto_20160526_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlistitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
